name: Convert to Linux

on:
  push:
    branches:
    - main

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: pnpm
        run_install: true
    - run: ./calias switch --mode lin
      env:
        AliasFolder: $github_workspace
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: converted to linux
        branch: linux
        status_options: '--untracked-files=yes'
        add_options: '--all'
