name: Convert to Linux

on:
  push:
    branches:
    - main

jobs:
  convert:
    name: Convert and Push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: true
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - run: ./calias switch --mode lin
      env:
        AliasFolder: ${{ github.workspace }}
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: converted to linux
        branch: linux
        add_options: '--all'
